<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zvt9SiOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zvt9SiO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zvt9SiO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profile' => ['privates', '.errored..service_locator.zvt9SiO.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.zvt9SiO": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\TimesheetRepository', 'getTimesheetRepositoryService', true],
            'statisticService' => ['privates', 'App\\Timesheet\\TimesheetStatisticService', 'getTimesheetStatisticServiceService', true],
        ], [
            'profile' => 'App\\Entity\\User',
            'repository' => 'App\\Repository\\TimesheetRepository',
            'statisticService' => 'App\\Timesheet\\TimesheetStatisticService',
        ]);
    }
}
