<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RnIgoETService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rnIgoET' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rnIgoET'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'roleService' => ['privates', 'App\\Security\\RoleService', 'getRoleServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'csrfTokenManager' => '?',
            'dispatcher' => '?',
            'roleService' => 'App\\Security\\RoleService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
