<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XAGY3GTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xAGY3GT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xAGY3GT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.xAGY3GT.App\\Entity\\Activity', NULL, 'Cannot autowire service ".service_locator.xAGY3GT": it needs an instance of "App\\Entity\\Activity" but this type has been excluded in "config/services.yaml".'],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', true],
        ], [
            'activity' => 'App\\Entity\\Activity',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);
    }
}
