<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XB8WOLgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xB8WOLg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xB8WOLg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'documentRepository' => ['privates', 'App\\Repository\\InvoiceDocumentRepository', 'getInvoiceDocumentRepositoryService', true],
        ], [
            'csrfTokenManager' => '?',
            'documentRepository' => 'App\\Repository\\InvoiceDocumentRepository',
        ]);
    }
}
