<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YC8F455Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YC8F455' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YC8F455'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'copyFrom' => ['privates', '.errored..service_locator.YC8F455.App\\Entity\\InvoiceTemplate', NULL, 'Cannot autowire service ".service_locator.YC8F455": it needs an instance of "App\\Entity\\InvoiceTemplate" but this type has been excluded in "config/services.yaml".'],
        ], [
            'copyFrom' => 'App\\Entity\\InvoiceTemplate',
        ]);
    }
}
