<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NX3VswuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NX3Vswu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NX3Vswu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'project' => ['privates', '.errored..service_locator.NX3Vswu.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.NX3Vswu": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'project' => 'App\\Entity\\Project',
        ]);
    }
}
