<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MCr_GCKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MCr.gCK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MCr.gCK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tag' => ['privates', '.errored..service_locator.MCr.gCK.App\\Entity\\Tag', NULL, 'Cannot autowire service ".service_locator.MCr.gCK": it needs an instance of "App\\Entity\\Tag" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tag' => 'App\\Entity\\Tag',
        ]);
    }
}
