<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HtMYj4hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.htMYj4h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.htMYj4h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'project' => ['privates', '.errored..service_locator.htMYj4h.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.htMYj4h": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
            'projectDuplicationService' => ['privates', 'App\\Project\\ProjectDuplicationService', 'getProjectDuplicationServiceService', true],
        ], [
            'csrfTokenManager' => '?',
            'project' => 'App\\Entity\\Project',
            'projectDuplicationService' => 'App\\Project\\ProjectDuplicationService',
        ]);
    }
}
