<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RkcZHVXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rkcZHVX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rkcZHVX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customer' => ['privates', '.errored..service_locator.rkcZHVX.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.rkcZHVX": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".'],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
        ], [
            'customer' => 'App\\Entity\\Customer',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
        ]);
    }
}
