<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JLCLYcUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JLCLYcU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JLCLYcU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cache' => ['services', 'cache.app', 'getCache_AppService', false],
            'client' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'manager' => ['privates', 'App\\Plugin\\PluginManager', 'getPluginManagerService', true],
        ], [
            'cache' => '?',
            'client' => '?',
            'manager' => 'App\\Plugin\\PluginManager',
        ]);
    }
}
