<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EwGXV3GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EwGXV3G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EwGXV3G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'paramFetcher' => ['privates', 'fos_rest.request.param_fetcher', 'getFosRest_Request_ParamFetcherService', false],
        ], [
            'customerRepository' => 'App\\Repository\\CustomerRepository',
            'paramFetcher' => '?',
        ]);
    }
}
