<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W6XrRj0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w6XrRj0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w6XrRj0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customer' => ['privates', '.errored..service_locator.w6XrRj0.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.w6XrRj0": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".'],
            'customerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'team' => ['privates', '.errored..service_locator.w6XrRj0.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.w6XrRj0": it needs an instance of "App\\Entity\\Team" but this type has been excluded in "config/services.yaml".'],
        ], [
            'customer' => 'App\\Entity\\Customer',
            'customerRepository' => 'App\\Repository\\CustomerRepository',
            'team' => 'App\\Entity\\Team',
        ]);
    }
}
