<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YIRacIgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yIRacIg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yIRacIg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'project' => ['privates', '.errored..service_locator.yIRacIg.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.yIRacIg": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
            'statisticService' => ['privates', 'App\\Project\\ProjectStatisticService', 'getProjectStatisticServiceService', true],
        ], [
            'project' => 'App\\Entity\\Project',
            'statisticService' => 'App\\Project\\ProjectStatisticService',
        ]);
    }
}
