<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1uafDBIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1uafDBI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1uafDBI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'role' => ['privates', '.errored..service_locator.1uafDBI.App\\Entity\\Role', NULL, 'Cannot autowire service ".service_locator.1uafDBI": it needs an instance of "App\\Entity\\Role" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'csrfTokenManager' => '?',
            'role' => 'App\\Entity\\Role',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
