<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3A7ZtpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._3A7Ztp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._3A7Ztp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entry' => ['privates', '.errored..service_locator._3A7Ztp.App\\Entity\\Timesheet', NULL, 'Cannot autowire service ".service_locator._3A7Ztp": it needs an instance of "App\\Entity\\Timesheet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entry' => 'App\\Entity\\Timesheet',
        ]);
    }
}
