<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oe3cC5OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oe3cC5O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oe3cC5O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statisticService' => ['privates', 'App\\Timesheet\\TimesheetStatisticService', 'getTimesheetStatisticServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'statisticService' => 'App\\Timesheet\\TimesheetStatisticService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
