<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3cCLfX3.App\Entity\Activity' shared service.
     *
     * @return \App\Entity\Activity
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3cCLfX3": it needs an instance of "App\\Entity\\Activity" but this type has been excluded in "config/services.yaml".');
    }
}
