<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityStatisticServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Activity\ActivityStatisticService' shared autowired service.
     *
     * @return \App\Activity\ActivityStatisticService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Activity'.\DIRECTORY_SEPARATOR.'ActivityStatisticService.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Activity\\ActivityStatisticService'])) {
            return $container->privates['App\\Activity\\ActivityStatisticService'];
        }

        return $container->privates['App\\Activity\\ActivityStatisticService'] = new \App\Activity\ActivityStatisticService(($container->privates['App\\Repository\\TimesheetRepository'] ?? $container->load('getTimesheetRepositoryService')), $a);
    }
}
