<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\API\CustomerController' shared autowired service.
     *
     * @return \App\API\CustomerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'API'.\DIRECTORY_SEPARATOR.'BaseApiController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'API'.\DIRECTORY_SEPARATOR.'CustomerController.php';

        $container->services['App\\API\\CustomerController'] = $instance = new \App\API\CustomerController(($container->services['fos_rest.view_handler'] ?? self::getFosRest_ViewHandlerService($container)), ($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->privates['App\\Repository\\CustomerRateRepository'] ?? $container->load('getCustomerRateRepositoryService')), ($container->privates['App\\Customer\\CustomerService'] ?? $container->load('getCustomerServiceService')));

        $instance->setContainer(($container->privates['.service_locator.ADQFtKj'] ?? $container->load('get_ServiceLocator_ADQFtKjService'))->withContext('App\\API\\CustomerController', $container));

        return $instance;
    }
}
