<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerMonthlyProjectsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Reporting\CustomerMonthlyProjects\CustomerMonthlyProjectsRepository' shared autowired service.
     *
     * @return \App\Reporting\CustomerMonthlyProjects\CustomerMonthlyProjectsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Reporting'.\DIRECTORY_SEPARATOR.'CustomerMonthlyProjects'.\DIRECTORY_SEPARATOR.'CustomerMonthlyProjectsRepository.php';

        return $container->privates['App\\Reporting\\CustomerMonthlyProjects\\CustomerMonthlyProjectsRepository'] = new \App\Reporting\CustomerMonthlyProjects\CustomerMonthlyProjectsRepository(($container->privates['App\\Repository\\TimesheetRepository'] ?? $container->load('getTimesheetRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
