<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerStatisticServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Customer\CustomerStatisticService' shared autowired service.
     *
     * @return \App\Customer\CustomerStatisticService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Customer'.\DIRECTORY_SEPARATOR.'CustomerStatisticService.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Customer\\CustomerStatisticService'])) {
            return $container->privates['App\\Customer\\CustomerStatisticService'];
        }

        return $container->privates['App\\Customer\\CustomerStatisticService'] = new \App\Customer\CustomerStatisticService(($container->privates['App\\Repository\\TimesheetRepository'] ?? $container->load('getTimesheetRepositoryService')), $a);
    }
}
