<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomer11Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xRMdfNe.App\Entity\Customer' shared service.
     *
     * @return \App\Entity\Customer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xRMdfNe": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".');
    }
}
