<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportCreateCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ExportCreateCommand' shared autowired service.
     *
     * @return \App\Command\ExportCreateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ExportCreateCommand.php';

        $container->privates['App\\Command\\ExportCreateCommand'] = $instance = new \App\Command\ExportCreateCommand(($container->privates['App\\Export\\ServiceExport'] ?? $container->load('getServiceExportService')), ($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService')), ($container->privates['App\\Repository\\ProjectRepository'] ?? $container->load('getProjectRepositoryService')), ($container->privates['App\\Repository\\TeamRepository'] ?? $container->load('getTeamRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['App\\Mail\\KimaiMailer'] ?? $container->load('getKimaiMailerService')));

        $instance->setName('kimai:export:create');

        return $instance;
    }
}
