<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8uD4.Hd.App\Entity\Invoice' shared service.
     *
     * @return \App\Entity\Invoice
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8uD4.Hd": it needs an instance of "App\\Entity\\Invoice" but this type has been excluded in "config/services.yaml".');
    }
}
