<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceDocumentRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\InvoiceDocumentRepository' shared autowired service.
     *
     * @return \App\Repository\InvoiceDocumentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'InvoiceDocumentRepository.php';

        return $container->privates['App\\Repository\\InvoiceDocumentRepository'] = new \App\Repository\InvoiceDocumentRepository($container->parameters['kimai.invoice.documents']);
    }
}
