<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceCreateCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\InvoiceCreateCommand' shared autowired service.
     *
     * @return \App\Command\InvoiceCreateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'InvoiceCreateCommand.php';

        $container->privates['App\\Command\\InvoiceCreateCommand'] = $instance = new \App\Command\InvoiceCreateCommand(($container->privates['App\\Invoice\\ServiceInvoice'] ?? $container->load('getServiceInvoiceService')), ($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService')), ($container->privates['App\\Repository\\ProjectRepository'] ?? $container->load('getProjectRepositoryService')), ($container->privates['App\\Repository\\InvoiceTemplateRepository'] ?? $container->load('getInvoiceTemplateRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setName('kimai:invoice:create');

        return $instance;
    }
}
