<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLdapUserProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Ldap\LdapUserProvider' shared autowired service.
     *
     * @return \App\Ldap\LdapUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Ldap'.\DIRECTORY_SEPARATOR.'LdapUserProvider.php';

        $a = ($container->privates['App\\Ldap\\LdapManager'] ?? $container->load('getLdapManagerService'));

        if (isset($container->privates['App\\Ldap\\LdapUserProvider'])) {
            return $container->privates['App\\Ldap\\LdapUserProvider'];
        }

        return $container->privates['App\\Ldap\\LdapUserProvider'] = new \App\Ldap\LdapUserProvider($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
