<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLockdownServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Timesheet\LockdownService' shared autowired service.
     *
     * @return \App\Timesheet\LockdownService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'LockdownService.php';

        return $container->privates['App\\Timesheet\\LockdownService'] = new \App\Timesheet\LockdownService(($container->privates['App\\Configuration\\SystemConfiguration'] ?? self::getSystemConfigurationService($container)));
    }
}
