<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailTestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\MailTestCommand' shared autowired service.
     *
     * @return \App\Command\MailTestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'MailTestCommand.php';

        $container->privates['App\\Command\\MailTestCommand'] = $instance = new \App\Command\MailTestCommand(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setName('kimai:mail:test');
        $instance->setDescription('Send a test email');

        return $instance;
    }
}
