<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\ProjectType' shared autowired service.
     *
     * @return \App\Form\Type\ProjectType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ProjectType.php';

        return $container->privates['App\\Form\\Type\\ProjectType'] = new \App\Form\Type\ProjectType(($container->privates['App\\Form\\Helper\\ProjectHelper'] ?? $container->load('getProjectHelperService')), ($container->privates['App\\Form\\Helper\\CustomerHelper'] ?? $container->load('getCustomerHelperService')));
    }
}
