<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1.2RqhU.App\Entity\Project' shared service.
     *
     * @return \App\Entity\Project
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1.2RqhU": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".');
    }
}
