<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Plugin\PluginManager' shared autowired service.
     *
     * @return \App\Plugin\PluginManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'PluginManager.php';

        return $container->privates['App\\Plugin\\PluginManager'] = new \App\Plugin\PluginManager(new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }
}
