<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermissionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\User\PermissionService' shared autowired service.
     *
     * @return \App\User\PermissionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'PermissionService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RolePermissionRepository.php';

        return $container->privates['App\\User\\PermissionService'] = new \App\User\PermissionService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))->getRepository('App\\Entity\\RolePermission'), ($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
