<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRuntimeExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'KevinPapst\TablerBundle\Twig\RuntimeExtension' shared service.
     *
     * @return \KevinPapst\TablerBundle\Twig\RuntimeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'kevinpapst'.\DIRECTORY_SEPARATOR.'tabler-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'RuntimeExtension.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['KevinPapst\\TablerBundle\\Twig\\RuntimeExtension'])) {
            return $container->privates['KevinPapst\\TablerBundle\\Twig\\RuntimeExtension'];
        }

        return $container->privates['KevinPapst\\TablerBundle\\Twig\\RuntimeExtension'] = new \KevinPapst\TablerBundle\Twig\RuntimeExtension($a, ($container->privates['tabler_bundle.context_helper'] ?? self::getTablerBundle_ContextHelperService($container)), $container->parameters['tabler_bundle.routes'], $container->parameters['tabler_bundle.icons']);
    }
}
