<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReloadCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ReloadCommand' shared autowired service.
     *
     * @return \App\Command\ReloadCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ReloadCommand.php';

        $container->privates['App\\Command\\ReloadCommand'] = $instance = new \App\Command\ReloadCommand(\dirname(__DIR__, 4), 'dev');

        $instance->setName('kimai:reload');

        return $instance;
    }
}
