<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Timesheet\RateService' shared autowired service.
     *
     * @return \App\Timesheet\RateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'RateServiceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'RateService.php';

        $a = ($container->privates['App\\Repository\\TimesheetRepository'] ?? $container->load('getTimesheetRepositoryService'));

        if (isset($container->privates['App\\Timesheet\\RateService'])) {
            return $container->privates['App\\Timesheet\\RateService'];
        }

        return $container->privates['App\\Timesheet\\RateService'] = new \App\Timesheet\RateService([], $a);
    }
}
