<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSamlAuthFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Saml\SamlAuthFactory' shared autowired service.
     *
     * @return \App\Saml\SamlAuthFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Saml'.\DIRECTORY_SEPARATOR.'SamlAuthFactory.php';

        return $container->privates['App\\Saml\\SamlAuthFactory'] = new \App\Saml\SamlAuthFactory(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Configuration\\SamlConfiguration'] ?? $container->load('getSamlConfigurationService')));
    }
}
