<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeam3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jNCcCQk.App\Entity\Team' shared service.
     *
     * @return \App\Entity\Team
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jNCcCQk": it needs an instance of "App\\Entity\\Team" but this type has been excluded in "config/services.yaml".');
    }
}
