<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimesheetsTeamSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\Actions\TimesheetsTeamSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\Actions\TimesheetsTeamSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'AbstractActionsSubscriber.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'TimesheetsTeamSubscriber.php';

        $a = ($container->services['jms_serializer.authorization_checker'] ?? self::getJmsSerializer_AuthorizationCheckerService($container));

        if (isset($container->privates['App\\EventSubscriber\\Actions\\TimesheetsTeamSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\Actions\\TimesheetsTeamSubscriber'];
        }
        $b = ($container->privates['App\\Export\\ServiceExport'] ?? $container->load('getServiceExportService'));

        if (isset($container->privates['App\\EventSubscriber\\Actions\\TimesheetsTeamSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\Actions\\TimesheetsTeamSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\Actions\\TimesheetsTeamSubscriber'] = new \App\EventSubscriber\Actions\TimesheetsTeamSubscriber($a, ($container->services['router'] ?? self::getRouterService($container)), $b);
    }
}
