<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserExporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Export\Spreadsheet\UserExporter' shared autowired service.
     *
     * @return \App\Export\Spreadsheet\UserExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Export'.\DIRECTORY_SEPARATOR.'Spreadsheet'.\DIRECTORY_SEPARATOR.'UserExporter.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Export'.\DIRECTORY_SEPARATOR.'Spreadsheet'.\DIRECTORY_SEPARATOR.'Extractor'.\DIRECTORY_SEPARATOR.'ExtractorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Export'.\DIRECTORY_SEPARATOR.'Spreadsheet'.\DIRECTORY_SEPARATOR.'Extractor'.\DIRECTORY_SEPARATOR.'UserPreferenceExtractor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Export'.\DIRECTORY_SEPARATOR.'Spreadsheet'.\DIRECTORY_SEPARATOR.'Extractor'.\DIRECTORY_SEPARATOR.'AnnotationExtractor.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Export\\Spreadsheet\\UserExporter'])) {
            return $container->privates['App\\Export\\Spreadsheet\\UserExporter'];
        }

        return $container->privates['App\\Export\\Spreadsheet\\UserExporter'] = new \App\Export\Spreadsheet\UserExporter(($container->privates['App\\Export\\Spreadsheet\\SpreadsheetExporter'] ?? $container->load('getSpreadsheetExporterService')), ($container->privates['App\\Export\\Spreadsheet\\Extractor\\AnnotationExtractor'] ??= new \App\Export\Spreadsheet\Extractor\AnnotationExtractor()), new \App\Export\Spreadsheet\Extractor\UserPreferenceExtractor($a));
    }
}
