<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWidgetServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Widget\WidgetService' shared autowired service.
     *
     * @return \App\Widget\WidgetService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'WidgetService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'WidgetInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AbstractWidget.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AbstractWidgetType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ActiveTimesheets.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AbstractActiveUsers.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ActiveUsersMonth.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ActiveUsersToday.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ActiveUsersTotal.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ActiveUsersWeek.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AbstractCounterYear.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ActiveUsersYear.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AbstractAmountPeriod.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AmountMonth.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AmountToday.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AmountTotal.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AmountWeek.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AmountYear.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'DailyWorkingTimeChart.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AbstractCounterDuration.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'DurationMonth.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'DurationToday.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'DurationTotal.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'DurationWeek.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'DurationYear.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'PaginatedWorkingTimeChart.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TotalsActivity.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TotalsCustomer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TotalsProject.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'TotalsUser.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'AbstractUserRevenuePeriod.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserAmountMonth.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserAmountToday.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserAmountTotal.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserAmountWeek.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserAmountYear.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserDurationMonth.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserDurationToday.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserDurationTotal.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserDurationWeek.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserDurationYear.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserTeamProjects.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Widget'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'UserTeams.php';

        $container->privates['App\\Widget\\WidgetService'] = $instance = new \App\Widget\WidgetService();

        $a = ($container->privates['App\\Repository\\TimesheetRepository'] ?? $container->load('getTimesheetRepositoryService'));
        $b = ($container->privates['App\\Configuration\\SystemConfiguration'] ?? self::getSystemConfigurationService($container));
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        $instance->registerWidget(new \App\Widget\Type\ActiveTimesheets($a));
        $instance->registerWidget(new \App\Widget\Type\ActiveUsersMonth($a));
        $instance->registerWidget(new \App\Widget\Type\ActiveUsersToday($a));
        $instance->registerWidget(new \App\Widget\Type\ActiveUsersTotal($a));
        $instance->registerWidget(new \App\Widget\Type\ActiveUsersWeek($a));
        $instance->registerWidget(new \App\Widget\Type\ActiveUsersYear($a, $b));
        $instance->registerWidget(new \App\Widget\Type\AmountMonth($a, $c));
        $instance->registerWidget(new \App\Widget\Type\AmountToday($a, $c));
        $instance->registerWidget(new \App\Widget\Type\AmountTotal($a, $c));
        $instance->registerWidget(new \App\Widget\Type\AmountWeek($a, $c));
        $instance->registerWidget(new \App\Widget\Type\AmountYear($a, $b, $c));
        $instance->registerWidget(new \App\Widget\Type\DailyWorkingTimeChart($a));
        $instance->registerWidget(new \App\Widget\Type\DurationMonth($a));
        $instance->registerWidget(new \App\Widget\Type\DurationToday($a));
        $instance->registerWidget(new \App\Widget\Type\DurationTotal($a));
        $instance->registerWidget(new \App\Widget\Type\DurationWeek($a));
        $instance->registerWidget(new \App\Widget\Type\DurationYear($a, $b));
        $instance->registerWidget(new \App\Widget\Type\PaginatedWorkingTimeChart($a, $b));
        $instance->registerWidget(new \App\Widget\Type\TotalsActivity(($container->privates['App\\Repository\\ActivityRepository'] ?? $container->load('getActivityRepositoryService'))));
        $instance->registerWidget(new \App\Widget\Type\TotalsCustomer(($container->privates['App\\Repository\\CustomerRepository'] ?? $container->load('getCustomerRepositoryService'))));
        $instance->registerWidget(new \App\Widget\Type\TotalsProject(($container->privates['App\\Repository\\ProjectRepository'] ?? $container->load('getProjectRepositoryService'))));
        $instance->registerWidget(new \App\Widget\Type\TotalsUser(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'))));
        $instance->registerWidget(new \App\Widget\Type\UserAmountMonth($a, $c));
        $instance->registerWidget(new \App\Widget\Type\UserAmountToday($a, $c));
        $instance->registerWidget(new \App\Widget\Type\UserAmountTotal($a, $c));
        $instance->registerWidget(new \App\Widget\Type\UserAmountWeek($a, $c));
        $instance->registerWidget(new \App\Widget\Type\UserAmountYear($a, $b, $c));
        $instance->registerWidget(new \App\Widget\Type\UserDurationMonth($a));
        $instance->registerWidget(new \App\Widget\Type\UserDurationToday($a));
        $instance->registerWidget(new \App\Widget\Type\UserDurationTotal($a));
        $instance->registerWidget(new \App\Widget\Type\UserDurationWeek($a));
        $instance->registerWidget(new \App\Widget\Type\UserDurationYear($a, $b));
        $instance->registerWidget(new \App\Widget\Type\UserTeamProjects(($container->privates['App\\Project\\ProjectStatisticService'] ?? $container->load('getProjectStatisticServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));
        $instance->registerWidget(new \App\Widget\Type\UserTeams());

        return $instance;
    }
}
