<?php

namespace ContainerHQVrSX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWidgetExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Runtime\WidgetExtension' shared autowired service.
     *
     * @return \App\Twig\Runtime\WidgetExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Runtime'.\DIRECTORY_SEPARATOR.'WidgetExtension.php';

        $a = ($container->privates['App\\Widget\\WidgetService'] ?? $container->load('getWidgetServiceService'));

        if (isset($container->privates['App\\Twig\\Runtime\\WidgetExtension'])) {
            return $container->privates['App\\Twig\\Runtime\\WidgetExtension'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Twig\\Runtime\\WidgetExtension'])) {
            return $container->privates['App\\Twig\\Runtime\\WidgetExtension'];
        }

        return $container->privates['App\\Twig\\Runtime\\WidgetExtension'] = new \App\Twig\Runtime\WidgetExtension($a, $b);
    }
}
