<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qa59zDHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qa59zDH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qa59zDH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'loginLinkHandler' => ['privates', 'security.authenticator.firewall_aware_login_link_handler', 'getSecurity_Authenticator_FirewallAwareLoginLinkHandlerService', true],
            'resetPasswordLimiter' => ['privates', 'limiter.reset_password', 'getLimiter_ResetPasswordService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'csrfTokenManager' => '?',
            'loginLinkHandler' => '?',
            'resetPasswordLimiter' => '?',
            'translator' => '?',
        ]);
    }
}
