<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZSX8HnKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zSX8HnK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zSX8HnK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loginManager' => ['privates', 'App\\User\\LoginManager', 'getLoginManagerService', true],
        ], [
            'loginManager' => 'App\\User\\LoginManager',
        ]);
    }
}
