<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4Dcun0tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Dcun0t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Dcun0t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'accessTokenRepository' => ['privates', 'App\\Repository\\AccessTokenRepository', 'getAccessTokenRepositoryService', true],
            'profile' => ['privates', '.errored..service_locator.4Dcun0t.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.4Dcun0t": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'accessTokenRepository' => 'App\\Repository\\AccessTokenRepository',
            'profile' => 'App\\Entity\\User',
        ]);
    }
}
