<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mp8ZgCgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mp8ZgCg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mp8ZgCg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customer' => ['privates', '.errored..service_locator.mp8ZgCg.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.mp8ZgCg": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".'],
            'statisticService' => ['privates', 'App\\Customer\\CustomerStatisticService', 'getCustomerStatisticServiceService', true],
        ], [
            'customer' => 'App\\Entity\\Customer',
            'statisticService' => 'App\\Customer\\CustomerStatisticService',
        ]);
    }
}
