<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1_2RqhUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1.2RqhU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1.2RqhU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'project' => ['privates', '.errored..service_locator.1.2RqhU.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.1.2RqhU": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
        ], [
            'project' => 'App\\Entity\\Project',
        ]);
    }
}
