<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_93lrjJrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.93lrjJr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.93lrjJr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customer' => ['privates', '.errored..service_locator.93lrjJr.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.93lrjJr": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".'],
            'rate' => ['privates', '.errored..service_locator.93lrjJr.App\\Entity\\CustomerRate', NULL, 'Cannot autowire service ".service_locator.93lrjJr": it needs an instance of "App\\Entity\\CustomerRate" but this type has been excluded in "config/services.yaml".'],
        ], [
            'customer' => 'App\\Entity\\Customer',
            'rate' => 'App\\Entity\\CustomerRate',
        ]);
    }
}
