<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JVfXqyXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jVfXqyX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jVfXqyX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'template' => ['privates', '.errored..service_locator.jVfXqyX.App\\Entity\\InvoiceTemplate', NULL, 'Cannot autowire service ".service_locator.jVfXqyX": it needs an instance of "App\\Entity\\InvoiceTemplate" but this type has been excluded in "config/services.yaml".'],
        ], [
            'csrfTokenManager' => '?',
            'template' => 'App\\Entity\\InvoiceTemplate',
        ]);
    }
}
