<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ILUFW_YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ILUFW.Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ILUFW.Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exporter' => ['privates', 'App\\Export\\Spreadsheet\\UserExporter', 'getUserExporterService', true],
        ], [
            'exporter' => 'App\\Export\\Spreadsheet\\UserExporter',
        ]);
    }
}
