<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CV8rQ4bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cV8rQ4b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cV8rQ4b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customer' => ['privates', '.errored..service_locator.cV8rQ4b.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.cV8rQ4b": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".'],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', true],
        ], [
            'customer' => 'App\\Entity\\Customer',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);
    }
}
