<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CPgsbwOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CPgsbwO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CPgsbwO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.CPgsbwO.App\\Entity\\Activity', NULL, 'Cannot autowire service ".service_locator.CPgsbwO": it needs an instance of "App\\Entity\\Activity" but this type has been excluded in "config/services.yaml".'],
            'statisticService' => ['privates', 'App\\Activity\\ActivityStatisticService', 'getActivityStatisticServiceService', true],
        ], [
            'activity' => 'App\\Entity\\Activity',
            'statisticService' => 'App\\Activity\\ActivityStatisticService',
        ]);
    }
}
