<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J203bXBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J203bXB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J203bXB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profile' => ['privates', '.errored..service_locator.J203bXB.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.J203bXB": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'totpAuthenticator' => ['services', 'scheb_two_factor.security.totp_authenticator', 'getSchebTwoFactor_Security_TotpAuthenticatorService', true],
            'userService' => ['privates', 'App\\User\\UserService', 'getUserServiceService', true],
        ], [
            'profile' => 'App\\Entity\\User',
            'totpAuthenticator' => '?',
            'userService' => 'App\\User\\UserService',
        ]);
    }
}
