<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KHgZtRDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KHgZtRD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KHgZtRD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'project' => ['privates', '.errored..service_locator.KHgZtRD.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.KHgZtRD": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
            'rate' => ['privates', '.errored..service_locator.KHgZtRD.App\\Entity\\ProjectRate', NULL, 'Cannot autowire service ".service_locator.KHgZtRD": it needs an instance of "App\\Entity\\ProjectRate" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\ProjectRateRepository', 'getProjectRateRepositoryService', true],
        ], [
            'project' => 'App\\Entity\\Project',
            'rate' => 'App\\Entity\\ProjectRate',
            'repository' => 'App\\Repository\\ProjectRateRepository',
        ]);
    }
}
