<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMWdYSkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EMWdYSk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EMWdYSk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'timesheet' => ['privates', '.errored..service_locator.EMWdYSk.App\\Entity\\Timesheet', NULL, 'Cannot autowire service ".service_locator.EMWdYSk": it needs an instance of "App\\Entity\\Timesheet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'timesheet' => 'App\\Entity\\Timesheet',
        ]);
    }
}
