<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ErLUUUAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ErLUUUA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ErLUUUA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Reporting\\CustomerMonthlyProjects\\CustomerMonthlyProjectsRepository', 'getCustomerMonthlyProjectsRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'repository' => 'App\\Reporting\\CustomerMonthlyProjects\\CustomerMonthlyProjectsRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
