<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GwsaWd7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gwsaWd7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gwsaWd7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'systemConfiguration' => ['privates', 'App\\Configuration\\SystemConfiguration', 'getSystemConfigurationService', false],
        ], [
            'systemConfiguration' => 'App\\Configuration\\SystemConfiguration',
        ]);
    }
}
