<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4fhNv6jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4fhNv6j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4fhNv6j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'customerRepository' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'paramFetcher' => ['privates', 'fos_rest.request.param_fetcher', 'getFosRest_Request_ParamFetcherService', false],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'customerRepository' => 'App\\Repository\\CustomerRepository',
            'paramFetcher' => '?',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
