<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CE82m8pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cE82m8p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cE82m8p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'workingTimeService' => ['privates', 'App\\WorkingTime\\WorkingTimeService', 'getWorkingTimeServiceService', true],
        ], [
            'eventDispatcher' => '?',
            'workingTimeService' => 'App\\WorkingTime\\WorkingTimeService',
        ]);
    }
}
