<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9Zgf6EVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Zgf6EV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Zgf6EV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.9Zgf6EV.App\\Entity\\Activity', NULL, 'Cannot autowire service ".service_locator.9Zgf6EV": it needs an instance of "App\\Entity\\Activity" but this type has been excluded in "config/services.yaml".'],
            'rate' => ['privates', '.errored..service_locator.9Zgf6EV.App\\Entity\\ActivityRate', NULL, 'Cannot autowire service ".service_locator.9Zgf6EV": it needs an instance of "App\\Entity\\ActivityRate" but this type has been excluded in "config/services.yaml".'],
        ], [
            'activity' => 'App\\Entity\\Activity',
            'rate' => 'App\\Entity\\ActivityRate',
        ]);
    }
}
