<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GP0fiSaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gP0fiSa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gP0fiSa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'accessToken' => ['privates', '.errored..service_locator.gP0fiSa.App\\Entity\\AccessToken', NULL, 'Cannot autowire service ".service_locator.gP0fiSa": it needs an instance of "App\\Entity\\AccessToken" but this type has been excluded in "config/services.yaml".'],
            'accessTokenRepository' => ['privates', 'App\\Repository\\AccessTokenRepository', 'getAccessTokenRepositoryService', true],
        ], [
            'accessToken' => 'App\\Entity\\AccessToken',
            'accessTokenRepository' => 'App\\Repository\\AccessTokenRepository',
        ]);
    }
}
