<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JC51hWRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JC51hWR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JC51hWR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paramFetcher' => ['privates', 'fos_rest.request.param_fetcher', 'getFosRest_Request_ParamFetcherService', false],
        ], [
            'paramFetcher' => '?',
        ]);
    }
}
