<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XkKsHzXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XkKsHzX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XkKsHzX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activity' => ['privates', '.errored..service_locator.XkKsHzX.App\\Entity\\Activity', NULL, 'Cannot autowire service ".service_locator.XkKsHzX": it needs an instance of "App\\Entity\\Activity" but this type has been excluded in "config/services.yaml".'],
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', true],
            'team' => ['privates', '.errored..service_locator.XkKsHzX.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.XkKsHzX": it needs an instance of "App\\Entity\\Team" but this type has been excluded in "config/services.yaml".'],
        ], [
            'activity' => 'App\\Entity\\Activity',
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'team' => 'App\\Entity\\Team',
        ]);
    }
}
