<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STtJWJ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.STtJWJ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.STtJWJ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'permissionService' => ['privates', 'App\\User\\PermissionService', 'getPermissionServiceService', true],
            'role' => ['privates', '.errored..service_locator.STtJWJ6.App\\Entity\\Role', NULL, 'Cannot autowire service ".service_locator.STtJWJ6": it needs an instance of "App\\Entity\\Role" but this type has been excluded in "config/services.yaml".'],
        ], [
            'csrfTokenManager' => '?',
            'permissionService' => 'App\\User\\PermissionService',
            'role' => 'App\\Entity\\Role',
        ]);
    }
}
