<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTokenMigratingListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\API\Authentication\ApiTokenMigratingListener' shared autowired service.
     *
     * @return \App\API\Authentication\ApiTokenMigratingListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'API'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'ApiTokenMigratingListener.php';

        return $container->privates['App\\API\\Authentication\\ApiTokenMigratingListener'] = new \App\API\Authentication\ApiTokenMigratingListener(($container->privates['security.password_hasher_factory'] ?? $container->load('getSecurity_PasswordHasherFactoryService')));
    }
}
