<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssets_PackageAvatarsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'assets._package_avatars' shared service.
     *
     * @return \Symfony\Component\Asset\PathPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['assets._package_avatars'] = new \Symfony\Component\Asset\PathPackage('avatars', ($container->privates['assets._version__default'] ?? self::getAssets_VersionDefaultService($container)), ($container->privates['assets.context'] ?? self::getAssets_ContextService($container)));
    }
}
