<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\ActivityType' shared autowired service.
     *
     * @return \App\Form\Type\ActivityType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'ActivityType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'ActivityHelper.php';

        return $container->privates['App\\Form\\Type\\ActivityType'] = new \App\Form\Type\ActivityType(new \App\Form\Helper\ActivityHelper(($container->privates['App\\Configuration\\SystemConfiguration'] ?? self::getSystemConfigurationService($container))), ($container->privates['App\\Form\\Helper\\ProjectHelper'] ?? $container->load('getProjectHelperService')));
    }
}
