<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultModeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Timesheet\TrackingMode\DefaultMode' shared autowired service.
     *
     * @return \App\Timesheet\TrackingMode\DefaultMode
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'TrackingMode'.\DIRECTORY_SEPARATOR.'TrackingModeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'TrackingMode'.\DIRECTORY_SEPARATOR.'TrackingModeTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'TrackingMode'.\DIRECTORY_SEPARATOR.'AbstractTrackingMode.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'TrackingMode'.\DIRECTORY_SEPARATOR.'DefaultMode.php';

        return $container->privates['App\\Timesheet\\TrackingMode\\DefaultMode'] = new \App\Timesheet\TrackingMode\DefaultMode(($container->privates['App\\Timesheet\\RoundingService'] ?? $container->load('getRoundingServiceService')));
    }
}
