<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeactivateUserCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DeactivateUserCommand' shared autowired service.
     *
     * @return \App\Command\DeactivateUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DeactivateUserCommand.php';

        $container->privates['App\\Command\\DeactivateUserCommand'] = $instance = new \App\Command\DeactivateUserCommand(($container->privates['App\\User\\UserService'] ?? $container->load('getUserServiceService')));

        $instance->setName('kimai:user:deactivate');

        return $instance;
    }
}
