<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InvoiceController' shared autowired service.
     *
     * @return \App\Controller\InvoiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'InvoiceController.php';

        $container->services['App\\Controller\\InvoiceController'] = $instance = new \App\Controller\InvoiceController(($container->privates['App\\Invoice\\ServiceInvoice'] ?? $container->load('getServiceInvoiceService')), ($container->privates['App\\Repository\\InvoiceTemplateRepository'] ?? $container->load('getInvoiceTemplateRepositoryService')), ($container->privates['App\\Repository\\InvoiceRepository'] ?? $container->load('getInvoiceRepositoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setContainer(($container->privates['.service_locator.ibacmod'] ?? $container->load('get_ServiceLocator_IbacmodService'))->withContext('App\\Controller\\InvoiceController', $container));

        return $instance;
    }
}
