<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceArchiveSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\Actions\InvoiceArchiveSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\Actions\InvoiceArchiveSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'AbstractActionsSubscriber.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'InvoiceArchiveSubscriber.php';

        $a = ($container->services['jms_serializer.authorization_checker'] ?? self::getJmsSerializer_AuthorizationCheckerService($container));

        if (isset($container->privates['App\\EventSubscriber\\Actions\\InvoiceArchiveSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\Actions\\InvoiceArchiveSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\Actions\\InvoiceArchiveSubscriber'] = new \App\EventSubscriber\Actions\InvoiceArchiveSubscriber($a, ($container->services['router'] ?? self::getRouterService($container)));
    }
}
