<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceTemplate2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fO0Ryb9.App\Entity\InvoiceTemplate' shared service.
     *
     * @return \App\Entity\InvoiceTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fO0Ryb9": it needs an instance of "App\\Entity\\InvoiceTemplate" but this type has been excluded in "config/services.yaml".');
    }
}
