<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKimaiMailerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Mail\KimaiMailer' shared autowired service.
     *
     * @return \App\Mail\KimaiMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Mail'.\DIRECTORY_SEPARATOR.'KimaiMailer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Configuration'.\DIRECTORY_SEPARATOR.'MailConfiguration.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Mail\\KimaiMailer'])) {
            return $container->privates['App\\Mail\\KimaiMailer'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Mail\\KimaiMailer'])) {
            return $container->privates['App\\Mail\\KimaiMailer'];
        }

        return $container->privates['App\\Mail\\KimaiMailer'] = new \App\Mail\KimaiMailer(new \App\Configuration\MailConfiguration($container->getEnv('MAILER_FROM')), new \Symfony\Component\Mailer\Mailer($a, NULL, $b));
    }
}
