<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuBuilderSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\MenuBuilderSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\MenuBuilderSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'MenuBuilderSubscriber.php';

        $a = ($container->privates['App\\Utils\\MenuService'] ?? $container->load('getMenuServiceService'));

        if (isset($container->privates['App\\EventSubscriber\\MenuBuilderSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\MenuBuilderSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\MenuBuilderSubscriber'] = new \App\EventSubscriber\MenuBuilderSubscriber($a);
    }
}
