<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMPdfConverterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Pdf\MPdfConverter' shared autowired service.
     *
     * @return \App\Pdf\MPdfConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Pdf'.\DIRECTORY_SEPARATOR.'HtmlToPdfConverter.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Pdf'.\DIRECTORY_SEPARATOR.'MPdfConverter.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utils'.\DIRECTORY_SEPARATOR.'FileHelper.php';

        return $container->privates['App\\Pdf\\MPdfConverter'] = new \App\Pdf\MPdfConverter(($container->privates['App\\Utils\\FileHelper'] ??= new \App\Utils\FileHelper((\dirname(__DIR__, 4).'/var/data'))), $container->targetDir.'');
    }
}
