<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectDateRangeFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Reporting\ProjectDateRange\ProjectDateRangeForm' shared autowired service.
     *
     * @return \App\Reporting\ProjectDateRange\ProjectDateRangeForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Reporting'.\DIRECTORY_SEPARATOR.'ProjectDateRange'.\DIRECTORY_SEPARATOR.'ProjectDateRangeForm.php';

        return $container->privates['App\\Reporting\\ProjectDateRange\\ProjectDateRangeForm'] = new \App\Reporting\ProjectDateRange\ProjectDateRangeForm();
    }
}
