<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectRateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KHgZtRD.App\Entity\ProjectRate' shared service.
     *
     * @return \App\Entity\ProjectRate
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KHgZtRD": it needs an instance of "App\\Entity\\ProjectRate" but this type has been excluded in "config/services.yaml".');
    }
}
