<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPunchInOutModeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Timesheet\TrackingMode\PunchInOutMode' shared autowired service.
     *
     * @return \App\Timesheet\TrackingMode\PunchInOutMode
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'TrackingMode'.\DIRECTORY_SEPARATOR.'TrackingModeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'TrackingMode'.\DIRECTORY_SEPARATOR.'TrackingModeTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Timesheet'.\DIRECTORY_SEPARATOR.'TrackingMode'.\DIRECTORY_SEPARATOR.'PunchInOutMode.php';

        $a = ($container->services['jms_serializer.authorization_checker'] ?? self::getJmsSerializer_AuthorizationCheckerService($container));

        if (isset($container->privates['App\\Timesheet\\TrackingMode\\PunchInOutMode'])) {
            return $container->privates['App\\Timesheet\\TrackingMode\\PunchInOutMode'];
        }

        return $container->privates['App\\Timesheet\\TrackingMode\\PunchInOutMode'] = new \App\Timesheet\TrackingMode\PunchInOutMode($a);
    }
}
