<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceInvoiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Invoice\ServiceInvoice' shared autowired service.
     *
     * @return \App\Invoice\ServiceInvoice
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'ServiceInvoice.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'InvoiceModelFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'AbstractRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'RendererInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'DocxRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'AbstractSpreadsheetRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'OdsRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'AbstractTwigRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Export'.\DIRECTORY_SEPARATOR.'Base'.\DIRECTORY_SEPARATOR.'DispositionInlineInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Pdf'.\DIRECTORY_SEPARATOR.'PdfRendererTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'PdfRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'TwigRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Renderer'.\DIRECTORY_SEPARATOR.'XlsxRenderer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'NumberGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'NumberGenerator'.\DIRECTORY_SEPARATOR.'ConfigurableNumberGenerator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'NumberGenerator'.\DIRECTORY_SEPARATOR.'DateNumberGenerator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'AbstractCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'AbstractMergedCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'CalculatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'AbstractSumInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'ActivityInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'ActivityUserInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'DateInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'DateUserInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'DefaultCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'PriceInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'ProjectInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'ProjectUserInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'ShortInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'UserInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'Calculator'.\DIRECTORY_SEPARATOR.'WeeklyInvoiceCalculator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Invoice'.\DIRECTORY_SEPARATOR.'InvoiceItemRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'TimesheetInvoiceItemRepository.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utils'.\DIRECTORY_SEPARATOR.'FileHelper.php';

        $a = ($container->privates['App\\Repository\\InvoiceRepository'] ?? $container->load('getInvoiceRepositoryService'));

        $container->privates['App\\Invoice\\ServiceInvoice'] = $instance = new \App\Invoice\ServiceInvoice(($container->privates['App\\Repository\\InvoiceDocumentRepository'] ?? $container->load('getInvoiceDocumentRepositoryService')), ($container->privates['App\\Utils\\FileHelper'] ??= new \App\Utils\FileHelper((\dirname(__DIR__, 4).'/var/data'))), $a, ($container->privates['App\\Configuration\\LocaleService'] ?? self::getLocaleServiceService($container)), new \App\Invoice\InvoiceModelFactory(($container->privates['App\\Customer\\CustomerStatisticService'] ?? $container->load('getCustomerStatisticServiceService')), ($container->privates['App\\Project\\ProjectStatisticService'] ?? $container->load('getProjectStatisticServiceService')), ($container->privates['App\\Activity\\ActivityStatisticService'] ?? $container->load('getActivityStatisticServiceService'))));

        $b = ($container->privates['twig'] ?? self::getTwigService($container));

        $instance->addRenderer(new \App\Invoice\Renderer\DocxRenderer());
        $instance->addRenderer(new \App\Invoice\Renderer\OdsRenderer());
        $instance->addRenderer(new \App\Invoice\Renderer\PdfRenderer($b, ($container->privates['App\\Pdf\\MPdfConverter'] ?? $container->load('getMPdfConverterService'))));
        $instance->addRenderer(new \App\Invoice\Renderer\TwigRenderer($b));
        $instance->addRenderer(new \App\Invoice\Renderer\XlsxRenderer());
        $instance->addNumberGenerator(new \App\Invoice\NumberGenerator\ConfigurableNumberGenerator($a, ($container->privates['App\\Configuration\\SystemConfiguration'] ?? self::getSystemConfigurationService($container))));
        $instance->addNumberGenerator(new \App\Invoice\NumberGenerator\DateNumberGenerator($a));
        $instance->addCalculator(new \App\Invoice\Calculator\ActivityInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\ActivityUserInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\DateInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\DateUserInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\DefaultCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\PriceInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\ProjectInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\ProjectUserInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\ShortInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\UserInvoiceCalculator());
        $instance->addCalculator(new \App\Invoice\Calculator\WeeklyInvoiceCalculator());
        $instance->addInvoiceItemRepository(new \App\Repository\TimesheetInvoiceItemRepository(($container->privates['App\\Repository\\TimesheetRepository'] ?? $container->load('getTimesheetRepositoryService'))));

        return $instance;
    }
}
