<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_KernelExceptionListener_TwoFactor_SecuredAreaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.kernel_exception_listener.two_factor.secured_area' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\Http\Firewall\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'scheb'.\DIRECTORY_SEPARATOR.'2fa-bundle'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Firewall'.\DIRECTORY_SEPARATOR.'ExceptionListener.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['security.authentication.kernel_exception_listener.two_factor.secured_area'])) {
            return $container->privates['security.authentication.kernel_exception_listener.two_factor.secured_area'];
        }

        return $container->privates['security.authentication.kernel_exception_listener.two_factor.secured_area'] = new \Scheb\TwoFactorBundle\Security\Http\Firewall\ExceptionListener('secured_area', ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['security.authentication.authentication_required_handler.two_factor.secured_area'] ?? $container->load('getSecurity_Authentication_AuthenticationRequiredHandler_TwoFactor_SecuredAreaService')), $a);
    }
}
