<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Runtime\ThemeExtension' shared autowired service.
     *
     * @return \App\Twig\Runtime\ThemeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Runtime'.\DIRECTORY_SEPARATOR.'ThemeExtension.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Twig\\Runtime\\ThemeExtension'])) {
            return $container->privates['App\\Twig\\Runtime\\ThemeExtension'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Twig\\Runtime\\ThemeExtension'])) {
            return $container->privates['App\\Twig\\Runtime\\ThemeExtension'];
        }

        return $container->privates['App\\Twig\\Runtime\\ThemeExtension'] = new \App\Twig\Runtime\ThemeExtension($a, ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['App\\Configuration\\SystemConfiguration'] ?? self::getSystemConfigurationService($container)), $b);
    }
}
