<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolbarFormExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Extension\ToolbarFormExtension' shared autowired service.
     *
     * @return \App\Form\Extension\ToolbarFormExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'ToolbarFormExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'ToolbarHelper.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'TeamService.php';

        return $container->privates['App\\Form\\Extension\\ToolbarFormExtension'] = new \App\Form\Extension\ToolbarFormExtension(new \App\Form\Helper\ToolbarHelper(($container->privates['App\\User\\UserService'] ?? $container->load('getUserServiceService')), new \App\User\TeamService(($container->privates['App\\Repository\\TeamRepository'] ?? $container->load('getTeamRepositoryService')))));
    }
}
