<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimesheetRestartValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\Constraints\TimesheetRestartValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\TimesheetRestartValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'Constraints'.\DIRECTORY_SEPARATOR.'TimesheetRestartValidator.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Validator\\Constraints\\TimesheetRestartValidator'])) {
            return $container->privates['App\\Validator\\Constraints\\TimesheetRestartValidator'];
        }
        $b = ($container->privates['App\\Timesheet\\TrackingModeService'] ?? $container->load('getTrackingModeServiceService'));

        if (isset($container->privates['App\\Validator\\Constraints\\TimesheetRestartValidator'])) {
            return $container->privates['App\\Validator\\Constraints\\TimesheetRestartValidator'];
        }

        return $container->privates['App\\Validator\\Constraints\\TimesheetRestartValidator'] = new \App\Validator\Constraints\TimesheetRestartValidator($a, $b);
    }
}
