<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserYearControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Reporting\UserYearController' shared autowired service.
     *
     * @return \App\Controller\Reporting\UserYearController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Reporting'.\DIRECTORY_SEPARATOR.'AbstractUserReportController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Reporting'.\DIRECTORY_SEPARATOR.'UserYearController.php';

        $container->services['App\\Controller\\Reporting\\UserYearController'] = $instance = new \App\Controller\Reporting\UserYearController(($container->privates['App\\Timesheet\\TimesheetStatisticService'] ?? $container->load('getTimesheetStatisticServiceService')), ($container->privates['App\\Repository\\ProjectRepository'] ?? $container->load('getProjectRepositoryService')), ($container->privates['App\\Repository\\ActivityRepository'] ?? $container->load('getActivityRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ibacmod'] ?? $container->load('get_ServiceLocator_IbacmodService'))->withContext('App\\Controller\\Reporting\\UserYearController', $container));

        return $instance;
    }
}
