<?php

namespace ContainerMzr50d6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkingTimeModeFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\WorkingTime\Mode\WorkingTimeModeFactory' shared autowired service.
     *
     * @return \App\WorkingTime\Mode\WorkingTimeModeFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'WorkingTime'.\DIRECTORY_SEPARATOR.'Mode'.\DIRECTORY_SEPARATOR.'WorkingTimeModeFactory.php';

        return $container->privates['App\\WorkingTime\\Mode\\WorkingTimeModeFactory'] = new \App\WorkingTime\Mode\WorkingTimeModeFactory(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\WorkingTime\\Mode\\WorkingTimeModeDay'] ??= new \App\WorkingTime\Mode\WorkingTimeModeDay());
            yield 1 => ($container->privates['App\\WorkingTime\\Mode\\WorkingTimeModeNone'] ??= new \App\WorkingTime\Mode\WorkingTimeModeNone());
        }, 2));
    }
}
