<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \App\Entity\Customer implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'billable' => [parent::class, 'billable', null],
        "\0".parent::class."\0".'budget' => [parent::class, 'budget', null],
        "\0".parent::class."\0".'budgetType' => [parent::class, 'budgetType', null],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null],
        "\0".parent::class."\0".'company' => [parent::class, 'company', null],
        "\0".parent::class."\0".'contact' => [parent::class, 'contact', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'fax' => [parent::class, 'fax', null],
        "\0".parent::class."\0".'homepage' => [parent::class, 'homepage', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invoiceTemplate' => [parent::class, 'invoiceTemplate', null],
        "\0".parent::class."\0".'invoiceText' => [parent::class, 'invoiceText', null],
        "\0".parent::class."\0".'meta' => [parent::class, 'meta', null],
        "\0".parent::class."\0".'mobile' => [parent::class, 'mobile', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'number' => [parent::class, 'number', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'teams' => [parent::class, 'teams', null],
        "\0".parent::class."\0".'timeBudget' => [parent::class, 'timeBudget', null],
        "\0".parent::class."\0".'timezone' => [parent::class, 'timezone', null],
        "\0".parent::class."\0".'vatId' => [parent::class, 'vatId', null],
        "\0".parent::class."\0".'visible' => [parent::class, 'visible', null],
        'address' => [parent::class, 'address', null],
        'billable' => [parent::class, 'billable', null],
        'budget' => [parent::class, 'budget', null],
        'budgetType' => [parent::class, 'budgetType', null],
        'color' => [parent::class, 'color', null],
        'comment' => [parent::class, 'comment', null],
        'company' => [parent::class, 'company', null],
        'contact' => [parent::class, 'contact', null],
        'country' => [parent::class, 'country', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'currency' => [parent::class, 'currency', null],
        'email' => [parent::class, 'email', null],
        'fax' => [parent::class, 'fax', null],
        'homepage' => [parent::class, 'homepage', null],
        'id' => [parent::class, 'id', null],
        'invoiceTemplate' => [parent::class, 'invoiceTemplate', null],
        'invoiceText' => [parent::class, 'invoiceText', null],
        'meta' => [parent::class, 'meta', null],
        'mobile' => [parent::class, 'mobile', null],
        'name' => [parent::class, 'name', null],
        'number' => [parent::class, 'number', null],
        'phone' => [parent::class, 'phone', null],
        'teams' => [parent::class, 'teams', null],
        'timeBudget' => [parent::class, 'timeBudget', null],
        'timezone' => [parent::class, 'timezone', null],
        'vatId' => [parent::class, 'vatId', null],
        'visible' => [parent::class, 'visible', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
