<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activity extends \App\Entity\Activity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'billable' => [parent::class, 'billable', null],
        "\0".parent::class."\0".'budget' => [parent::class, 'budget', null],
        "\0".parent::class."\0".'budgetType' => [parent::class, 'budgetType', null],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null],
        "\0".parent::class."\0".'comment' => [parent::class, 'comment', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invoiceText' => [parent::class, 'invoiceText', null],
        "\0".parent::class."\0".'meta' => [parent::class, 'meta', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'number' => [parent::class, 'number', null],
        "\0".parent::class."\0".'project' => [parent::class, 'project', null],
        "\0".parent::class."\0".'teams' => [parent::class, 'teams', null],
        "\0".parent::class."\0".'timeBudget' => [parent::class, 'timeBudget', null],
        "\0".parent::class."\0".'visible' => [parent::class, 'visible', null],
        'billable' => [parent::class, 'billable', null],
        'budget' => [parent::class, 'budget', null],
        'budgetType' => [parent::class, 'budgetType', null],
        'color' => [parent::class, 'color', null],
        'comment' => [parent::class, 'comment', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'id' => [parent::class, 'id', null],
        'invoiceText' => [parent::class, 'invoiceText', null],
        'meta' => [parent::class, 'meta', null],
        'name' => [parent::class, 'name', null],
        'number' => [parent::class, 'number', null],
        'project' => [parent::class, 'project', null],
        'teams' => [parent::class, 'teams', null],
        'timeBudget' => [parent::class, 'timeBudget', null],
        'visible' => [parent::class, 'visible', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
